# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mult <- function(a, b) {
    .Call('bootR2_mult', PACKAGE = 'bootR2', a, b)
}

trans <- function(X) {
    .Call('bootR2_trans', PACKAGE = 'bootR2', X)
}

flm <- function(X, y) {
    .Call('fastLm', PACKAGE = 'RcppEigen', X, y, 0L)
}

crossProd <- function(X) {
    .Call('bootR2_crossProd', PACKAGE = 'bootR2', X)
}

betaHat <- function(X, y) {
    .Call('bootR2_betaHat', PACKAGE = 'bootR2', X, y)
}

R2 <- function(X, y) {
    .Call('bootR2_R2', PACKAGE = 'bootR2', X, y)
}

R2pred <- function(Xt, yt, Xv, yv) {
    .Call('bootR2_R2pred', PACKAGE = 'bootR2', Xt, yt, Xv, yv)
}

rUnif <- function(n) {
    .Call('bootR2_rUnif', PACKAGE = 'bootR2', n)
}

bootPerm <- function(n) {
    .Call('bootR2_bootPerm', PACKAGE = 'bootR2', n)
}

bootCoef <- function(X, y, nBoot) {
    .Call('bootR2_bootCoef', PACKAGE = 'bootR2', X, y, nBoot)
}



shuffleMatrix <- function(X, prm) {
    .Call('bootR2_shuffleMatrix', PACKAGE = 'bootR2', X, prm)
}

shuffleVector <- function(y, prm) {
    .Call('bootR2_shuffleVector', PACKAGE = 'bootR2', y, prm)
}

order_ <- function(x) {
    .Call('bootR2_order_', PACKAGE = 'bootR2', x)
}

dev <- function(y) {
    .Call('bootR2_dev', PACKAGE = 'bootR2', y)
}


##' The main functions for the package
##'
##' \code{bootR2pred} gives out-of-sample bootstrap
##' samples of R-squared, whereas \code{bootR2samp}
##' gives within-sample R-squared bootstrap samples
##' 
##' @param X model matrix
##' @param y model response
##' @param nBoot number of bootstrap samples
##' @return vector of \code{nBoot} R-squared values
bootR2pred <- function(X, y, nBoot) {
    .Call('bootR2_bootR2pred', PACKAGE = 'bootR2', X, y, nBoot)
}
bootR2samp <- function(X, y, nBoot) {
    .Call('bootR2_bootR2', PACKAGE = 'bootR2', X, y, nBoot)
}

